# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Fechas',
            },
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='gasto',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='monto',
        ),
        migrations.AddField(
            model_name='detalle',
            name='gasto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Gasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Fecha'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Fecha'),
        ),
    ]
