# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20171013_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anotaciones',
            new_name='Anotacion',
        ),
        migrations.RenameModel(
            old_name='Galpones',
            new_name='Galpon',
        ),
        migrations.RenameModel(
            old_name='Planteles',
            new_name='Plantel',
        ),
        migrations.RenameModel(
            old_name='Privilegios',
            new_name='Privilegio',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
