# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 23:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20171029_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='muertes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='postura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
