# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_galpon_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
